eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080

spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: user-service
          uri: http://localhost:8083/
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}

        - id: doctor-service
          uri: http://localhost:8087/
          predicates:
            - Path=/doctor-service/**
          filters:
            - RewritePath=/doctor-service(?<segment>/?.*), $\{segment}

        - id: caretaker-service
          uri: http://localhost:8082/
          predicates:
            - Path=/caretaker-service/**
          filters:
            - RewritePath=/caretaker-service(?<segment>/?.*), $\{segment}

        - id: book-appointment-service
          uri: http://localhost:8085/
          predicates:
            - Path=/book-appointment-service/**
          filters:
            - RewritePath=/book-appointment-service(?<segment>/?.*), $\{segment}

        - id: search-service
          uri: http://localhost:8081/
          predicates:
            - Path=/search-service/**
          filters:
            - RewritePath=/search-service(?<segment>/?.*), $\{segment}

        - id: user-auth-service
          uri: http://localhost:8888/
          predicates:
            - Path=/user-auth-service/**
          filters:
            - RewritePath=/user-auth-service(?<segment>/?.*), $\{segment}

        - id: payment-service
          uri: http://localhost:8089/
          predicates:
            - Path=/payment-service/**
          filters:
            - RewritePath=/payment-service(?<segment>/?.*), $\{segment}

        - id: chat-service
          uri: http://localhost:9099/
          predicates:
            - Path=/chat-service/**
          filters:
            - RewritePath=/chat-service(?<segment>/?.*), $\{segment}

        - id: schedular-service
          uri: http://localhost:8086/
          predicates:
            - Path=/schedular-service/**
          filters:
            - RewritePath=/schedular-service(?<segment>/?.*), $\{segment}

        - id: recommendation-service
          uri: http://localhost:8099/
          predicates:
            - Path=/recommendation-service/**
          filters:
            - RewritePath=/recommendation-service(?<segment>/?.*), $\{segment}

        - id: product-webapp
          uri: http://localhost:4200/
          predicates:
            - Path=/**
          filters:
            - RewritePath=(?<segment>/?.*), $\{segment}




management:
  endpoints:
    web:
      exposure:
        include: "*"